# Generated by Django 5.2.3 on 2025-07-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0002_productsdata_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cartlist', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productsdata',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
