# Generated by Django 5.2.3 on 2025-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0003_orderlist_alter_productsdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='cartlist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
