# Generated by Django 5.2.3 on 2025-07-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0004_alter_orderlist_address_alter_orderlist_cartlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='cartlist',
            field=models.JSONField(null=True),
        ),
    ]
