# Generated by Django 5.2.3 on 2025-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0005_orderlist_total_price_alter_orderlist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
