services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn yourprojectname.wsgi"
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: yourprojectname.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
